### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by pR0Ps** [GermainZ/PlayPermissionsExposed#12]
Causes a crash when installing/updating apps. Play store version 5.10.30 on Android 4.4.4 on a Nexus 5.

Relevant logs:

```
11-04 06:44:43.976 E/AndroidRuntime(32316): FATAL EXCEPTION: main
11-04 06:44:43.976 E/AndroidRuntime(32316): Process: com.android.vending, PID: 32316
11-04 06:44:43.976 E/AndroidRuntime(32316): java.lang.NoSuchFieldError: com.google.android.finsky.layout.AppPermissionAdapter#mData
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:80)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:611)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.germainz.playpermissionsexposed.XposedMod$2.replaceHookedMethod(XposedMod.java:199)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:15)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.layout.AppPermissionAdapter.getCount(Native Method)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.layout.AppSecurityPermissions.showPermissions(AppSecurityPermissions.java:81)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.layout.AppSecurityPermissions.bindInfo(AppSecurityPermissions.java:70)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.activities.AppsPermissionsActivity.onDataChanged(AppsPermissionsActivity.java:7342)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.api.model.DfeModel.notifyDataSetChanged(DfeModel.java:104)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.api.model.DfeDetails.onResponse(DfeDetails.java:1091)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.google.android.finsky.api.DfeRequest.deliverResponse(DfeRequest.java:20726)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at android.os.Handler.handleCallback(Handler.java:733)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at android.os.Looper.loop(Looper.java:136)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at java.lang.reflect.Method.invoke(Method.java:515)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
11-04 06:44:43.976 E/AndroidRuntime(32316): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by RunningDroid** [comment]
I get a slightly different crash with Play Store v 5.10.30 on Android 5.1.1 on a Samsung S6, probably because i'm using a different version of Xposed

```
E/AndroidRuntime(18274): FATAL EXCEPTION: main
E/AndroidRuntime(18274): Process: com.android.vending, PID: 18274
E/AndroidRuntime(18274): java.lang.NoSuchFieldError: com.google.android.finsky.layout.AppPermissionAdapter#mData
E/AndroidRuntime(18274): 	at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:82)
E/AndroidRuntime(18274): 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:613)
E/AndroidRuntime(18274): 	at com.germainz.playpermissionsexposed.XposedMod$2.replaceHookedMethod(XposedMod.java:199)
E/AndroidRuntime(18274): 	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:15)
E/AndroidRuntime(18274): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:653)
E/AndroidRuntime(18274): 	at com.google.android.finsky.layout.AppPermissionAdapter.getCount(<Xposed>)
E/AndroidRuntime(18274): 	at com.google.android.finsky.layout.AppSecurityPermissions.showPermissions(AppSecurityPermissions.java:81)
E/AndroidRuntime(18274): 	at com.google.android.finsky.layout.AppSecurityPermissions.bindInfo(AppSecurityPermissions.java:70)
E/AndroidRuntime(18274): 	at com.google.android.finsky.activities.AppsPermissionsActivity.onDataChanged(AppsPermissionsActivity.java:7342)
E/AndroidRuntime(18274): 	at com.google.android.finsky.api.model.DfeModel.notifyDataSetChanged(DfeModel.java:104)
E/AndroidRuntime(18274): 	at com.google.android.finsky.api.model.DfeDetails.onResponse(DfeDetails.java:1091)
E/AndroidRuntime(18274): 	at com.google.android.finsky.api.DfeRequest.deliverResponse(DfeRequest.java:20726)
E/AndroidRuntime(18274): 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
E/AndroidRuntime(18274): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(18274): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(18274): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(18274): 	at android.app.ActivityThread.main(ActivityThread.java:6837)
E/AndroidRuntime(18274): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18274): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(18274): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(18274): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
E/AndroidRuntime(18274): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```

**Comment by Efreak** [comment]
I'm getting a crash on Google play as well when I attempt to update our install new apps, unfortunately it's difficult to actually provide the error log as there's too much spam from other modules and mpdecision. I'm running xposed 75 and Google play version is 5.10.30, on a nexus 7 (2013) running Cyanogenmod nightly 20151107. If you need another log anyways, let me know and I'll disable the apps spamming my logcat, or figure out some way to filter it; otherwise I think it's safe to assume it's the same issue.

**Comment by eljoest** [comment]
I can confirm thr 5.1.1 crash: Play Store 5.10.30 on Android 5.1.1/cm12.1, xposed v75
Only change since before the crashes seems to be the play store version. 

```
java.lang.NoSuchFieldError: com.google.android.finsky.layout.AppPermissionAdapter#mData
    at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:82)
    at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:613)
    at com.germainz.playpermissionsexposed.XposedMod$2.replaceHookedMethod(XposedMod.java:199)
    at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:15)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:648)
    at com.google.android.finsky.layout.AppPermissionAdapter.getCount(<Xposed>)
    at com.google.android.finsky.layout.AppSecurityPermissions.showPermissions(AppSecurityPermissions.java:81)
    at com.google.android.finsky.layout.AppSecurityPermissions.bindInfo(AppSecurityPermissions.java:70)
    at com.google.android.finsky.activities.InstallApprovalFragment.onCreateView(InstallApprovalFragment.java:1128)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
    at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
    at android.app.Activity.performStart(Activity.java:6006)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
    at android.app.ActivityThread.access$900(ActivityThread.java:154)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5294)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)
```
